#!/bin/bash                                                                                                                                                        
im1=$1.nii.gz
im2=$2.nii.gz

ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=124

echo NOW WARPING $im1 to $im2

antsRegistration --dimensionality 3 --float 0 \
        --output [${im1}_to_${im2}_,${im1}_to_${im2}_Warped.nii.gz] \
        --interpolation Linear \
        --winsorize-image-intensities [0.005,0.995] \
        --use-histogram-matching 0 \
        --initial-moving-transform [$im2,$im1,1] \
        --transform Rigid[0.1] \
        --metric MI[$im2,$im1,1,32,Regular,0.25] \
        --convergence [1000x500x250x100,1e-6,10] \
        --shrink-factors 8x4x2x1 \
        --smoothing-sigmas 3x2x1x0vox \
        --transform Affine[0.1] \
        --metric MI[$im2,$im1,1,32,Regular,0.25] \
        --convergence [1000x500x250x100,1e-6,10] \
        --shrink-factors 8x4x2x1 \
        --smoothing-sigmas 3x2x1x0vox \
        --transform SyN[0.1,3,0] \
        --metric CC[$im2,$im1,1,4] \
        --convergence [100x70x50x20,1e-6,10] \
        --shrink-factors 8x4x2x1 \
        --smoothing-sigmas 3x2x1x0vox