#!/bin/bash                                                                                                                                                        
ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=124

source=$1
target=$2

echo ANTS...
ANTS 3 -m PR[$target.nii.gz,$source.nii.gz,1,2] -i 50x20x10 -o ${source}2${target}_synants.nii.gz -t SyN[0.3] -r Gauss[3,0]

echo Warp...
WarpImageMultiTransform 3 $source.nii.gz ${source}2${target}_warped_synants.nii.gz -R $target.nii.gz ${source}2${target}_synantsWarp.nii.gz ${source}2${target}_sy\
nantsAffine.txt