#!/bin/bash

list=$1
threads=256
#threadsX2=$((${threads}*2))

hbn=/lus/theta-fs0/projects/AD_Brain_Imaging/anal/hbn

CMD_batch=/lus/theta-fs0/projects/AD_Brain_Imaging/anal/hbn/code_hbn_alcf/job/cmd1.batch.trac.${list}
rm -rf $CMD_batch

#######################################################################################################
cat<<EOC >$CMD_batch
#!/bin/bash
#COBALT -t 720
#COBALT -n 1000
#COBALT --attrs mcdram=cache:numa=quad 
#COBALT --attrs ssds=required:ssd_size=100
#COBALT -A AD_Brain_Imaging
echo start............................................
#export n_nodes=$COBALT_JOBSIZE
#export n_mpi_ranks_per_node=202
#export n_mpi_ranks=202
#export n_openmp_threads_per_rank=64
#export n_hyperthreads_per_core=4
EOC

#######################################################################################################
i=1
for s in `cat /lus/theta-fs0/projects/AD_Brain_Imaging/anal/hbn/fs/\$list`
do
#s=`echo $SUBJECT | egrep -o '[0-9]{8}'`
CMD=/lus/theta-fs0/projects/AD_Brain_Imaging/anal/hbn/code_hbn_alcf/job/cmd1.trac.${s}
rm -rf $CMD

CMD_sub=/lus/theta-fs0/projects/AD_Brain_Imaging/anal/code_hbn_alcf/job/cmd1_sub.trac.${s}
rm -rf $CMD_sub


SUBJECT=${s}
#echo ${SUBJECT}

cat<<EOC >$CMD
#!/bin/bash
source ~/.bashrc
workingdir=/lus/theta-fs0/projects/AD_Brain_Imaging/anal/hbn/fs/${SUBJECT}/dmri2
mkdir -p \$workingdir

dwidir=

currentdir=/local/scratch/dmri2
mkdir -p \$currentdir
cd \$currentdir
echo current folder is `pwd`

ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=256

#%% 1. setup %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
ln -s /lus/theta-fs0/projects/AD_Brain_Imaging/anal/HBN/data/${s}/dwi/*_dwi.nii.gz ./dti.nii.gz
ln -s /lus/theta-fs0/projects/AD_Brain_Imaging/anal/HBN/data/${s}/dwi/*_dwi.bvec ./dti.bvec
ln -s /lus/theta-fs0/projects/AD_Brain_Imaging/anal/HBN/data/${s}/dwi/*_dwi.bval ./dti.bval
ln -s /lus/theta-fs0/projects/AD_Brain_Imaging/anal/HBN/data/${s}/dwi/*_dwi.json ./dti.json

ln -s /lus/theta-fs0/projects/AD_Brain_Imaging/anal/HBN/data/${s}/fmap/*AP_acq-dwi_epi.json ./dwi_fmap_AP.json
ln -s /lus/theta-fs0/projects/AD_Brain_Imaging/anal/HBN/data/${s}/fmap/*AP_acq-dwi_epi.nii.gz ./dwi_fmap_AP.nii.gz
ln -s /lus/theta-fs0/projects/AD_Brain_Imaging/anal/HBN/data/${s}/fmap/*PA_acq-dwi_epi.json ./dwi_fmap_PA.json
ln -s /lus/theta-fs0/projects/AD_Brain_Imaging/anal/HBN/data/${s}/fmap/*PA_acq-dwi_epi.nii.gz ./dwi_fmap_PA.nii.gz
#cp /ifs/scratch/pimri/posnerlab/1anal/adni/data/nii/${s}_*DTI.bvec_tp ./dti.bvec_tp
#cp /ifs/scratch/pimri/posnerlab/1anal/adni/data/nii/${s}_*DTI.bval_tp ./dti.bval_tp
#%% 2. DWI processing2-converting nifti to mif%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

# 1. mrconvert
if [ ! -e mr_dwi.mif ];then
    mrconvert dti.nii.gz -force mr_dwi.mif -fslgrad dti.bvec dti.bval -datatype float32 -stride 0,0,0,1 -nthreads 256
fi

# 2. denoising (time:1.2m)
if [ ! -e mr_dwi_denoised.mif ];then
    dwidenoise mr_dwi.mif -force mr_dwi_denoised.mif -nthreads 256
fi

# 3. gibss ringing (time:0.5m)
if [ ! -e mr_dwi_denoised_gibbs.mif ];then
    mrdegibbs mr_dwi_denoised.mif mr_dwi_denoised_gibbs.mif -force -nthreads 256
fi

# 4. dwipreproc -eddy current (time:79m)
if [ ! -e mr_dwi_denoised_gibbs_crop_preproc.mif ];then
    mrcat dwi_fmap_AP.nii.gz dwi_fmap_PA.nii.gz b0s.mif -axis 3 -nthreads 256
    
    mrcrop b0s.mif b0s_crop.mif -axis 2 1 80 -force
    
    mrcrop mr_dwi_denoised_gibbs.mif mr_dwi_denoised_gibbs_crop.mif -axis 2 1 80 -force
    
    time dwipreproc mr_dwi_denoised_gibbs_crop.mif mr_dwi_denoised_gibbs_crop_preproc.mif \
-json_import dti.json \
-se_epi b0s_crop.mif \
-pe_dir AP \
-rpe_pair \
-fslgrad dti.bvec dti.bval \
-eddy_options " --repol " \
-nthreads 256 \
-nocleanup

##########-readout_time 0.0691181 \#############??????????????????????????????\

fi

# 5. mask and bias field correction
if [ ! -e mr_eroded_mask.mif ]; then
     dwi2mask mr_dwi_denoised_gibbs_crop_preproc.mif - -nthreads 256 | maskfilter - erode -npass 3 -force mr_eroded_mask.mif -nthreads 256
fi

#%% 6. bias field correction (time: 0.5m)
if [ ! -e mr_dwi_denoised_gibbs_crop_preproc_biasCorr.mif ]; then
     dwibiascorrect mr_dwi_denoised_gibbs_crop_preproc.mif -force mr_dwi_denoised_gibbs_crop_preproc_biasCorr.mif -ants -nthreads 256 -mask mr_eroded_mask.mif
fi

#%% 7. generating b0 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if [ ! -e mr_meanb0.mif ];then
     dwiextract mr_dwi_denoised_gibbs_crop_preproc_biasCorr.mif - -bzero -nthreads 256 | mrmath - mean -force mr_meanb0.mif -axis 3 -nthreads 256 
fi

#%% 8. upsampling %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for im in mr_dwi_denoised_gibbs_crop_preproc_biasCorr mr_eroded_mask mr_meanb0;
do 
     if [ ! -e \${im}_upsample125.mif ];then
     mrresize \${im}.mif -voxel 1.25 -force \${im}_upsample125.mif -interp sinc -nthreads 256
     fi
done

#%% 9. dwi2response-subject level %%%%%%%%%%%  (time: 1.2m)
if [ ! -e response_wm.txt ]; then
    time dwi2response dhollander -mask mr_eroded_mask_upsample125.mif -voxels mr_voxels_eroded_upsample125.mif mr_dwi_denoised_gibbs_crop_preproc_biasCorr_upsample125.mif response_wm.txt response_gm.txt response_csf.txt -force -nthreads 256
fi
#%% FOD%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#% make sure to use "DILATED MASK" for FOD generation
if [ ! -e mr_dilate_mask.mif.gz ];then
    dwi2mask mr_dwi_denoised_gibbs_crop_preproc_biasCorr_upsample125.mif - -nthreads 256 | maskfilter - dilate -npass 3 -force mr_dilate_mask_upsample125.mif -nthreads 256
fi

### FOD estimation (time: 3m)
if [ ! -e WM_FODs_upsample125.mif ];then 
   time dwi2fod msmt_csd mr_dwi_denoised_gibbs_crop_preproc_biasCorr_upsample125.mif response_wm.txt WM_FODs_upsample125.mif response_gm.txt gm.mif response_csf.txt csf.mif -mask mr_dilate_mask_upsample125.mif -force -nthreads 256
fi

if [ ! -e tissueRGB.mif.gz ]; then
   mrconvert WM_FODs_upsample125.mif - -coord 3 0 -nthreads 256 | mrcat csf.mif gm.mif - tissueRGB.mif -axis 3 -nthreads 256
fi

### this is crucial to make the FODs comparable across subjects### (time: 1m)
    mtnormalise WM_FODs_upsample125.mif WM_FODs_upsample125_norm.mif gm.mif gm_norm.mif csf.mif csf_norm.mif -mask mr_dilate_mask_upsample125.mif -nthreads 256
    
mrconvert mr_dwi_denoised_gibbs_crop_preproc_biasCorr_upsample125.mif mr_dwi_denoised_gibbs_crop_preproc_biasCorr_upsample125.nii -force -nthreads 256
mrconvert mr_dilate_mask_upsample125.mif mr_dilate_mask_upsample125.nii -force -nthreads 256
dtifit -k mr_dwi_denoised_gibbs_crop_preproc_biasCorr_upsample125.nii -o dtifit -m mr_dilate_mask_upsample125.nii -r dti.bvec -b dti.bval -V


echo "I THINK EVERYTHING IS DONE BY NOW"
EOC

chmod +x $CMD

####################################################################
cat<<EOA >$CMD_sub
#!/bin/bash
#COBALT -t 60
#COBALT -n 1
#COBALT --attrs mcdram=cache:numa=quad
#COBALT -A AD_Brain_Imaging
echo start............................................
#export n_nodes=$COBALT_JOBSIZE
#export n_mpi_ranks_per_node=202
#export n_mpi_ranks=202
#export n_openmp_threads_per_rank=64
#export n_hyperthreads_per_core=4
aprun -n 1 -N 1 -d 1 -j 4 -cc depth -e OMP_NUM_THREADS=256 -cc depth $CMD
EOA
#####################################################################

chmod +x $CMD_sub


echo "aprun -n 1 -N 1 -j 4 -cc depth -e OMP_NUM_THREADS=256 $CMD > cmd1.log.${SUBJECT} &">>$CMD_batch
echo "sleep 0.2">>$CMD_batch
i=$(($i+1))
echo $i
#echo "execute $CMD_sub"

done

echo "wait" >> $CMD_batch
### batch submission

echo $CMD_batch
chmod +x $CMD_batch
echo "qsub $CMD_batch"
#$code/fsl_sub_hpc_2 -s smp,$threads -l /ifs/scratch/pimri/posnerlab/1anal/adni/adni_on_c2b2/job -t $CMD_batch
#$code/fsl_sub_hpc_6 -l /ifs/scratch/pimri/posnerlab/1anal/adni/adni_on_c2b2/job -t $CMD_batch
