#!/bin/bash

list=$1
N=`wc ${1} | awk '{print $1}'`
threads=128
#threadsX2=$((${threads}*2))

hbn=/lus/theta-fs0/projects/AD_Brain_Imaging/anal/hbn

CMD_batch=/lus/theta-fs0/projects/AD_Brain_Imaging/anal/HBN/code_hbn_alcf/job/cmd2.batch.trac.${list}
rm -rf $CMD_batch

#######################################################################################################
cat<<EOC >$CMD_batch
#!/bin/bash
#COBALT -t 01:00:00
#COBALT debug-cache-quad
#COBALT -n $N
#COBALT --attrs mcdram=cache:numa=quad:ssds=required:ssd_size=128 
#COBALT -A AD_Brain_Imaging
#COBALT -M jiook.cha@nyspi.columbia.edu
#COBALT ATP_ENABLED=1
echo start............................................
#export n_nodes=\$COBALT_JOBSIZE
#export n_mpi_ranks_per_node=1
#export n_mpi_ranks=1
#export n_openmp_threads_per_rank=64
#export n_hyperthreads_per_core=4
EOC

#######################################################################################################
i=1
for s in `cat /lus/theta-fs0/projects/AD_Brain_Imaging/anal/HBN/code_hbn_alcf/\$list`
            
do
#s=`echo $SUBJECT | egrep -o '[0-9]{8}'`
CMD=/lus/theta-fs0/projects/AD_Brain_Imaging/anal/HBN/code_hbn_alcf/job/cmd2.trac.${s}
rm -rf $CMD

LOG=/lus/theta-fs0/projects/AD_Brain_Imaging/anal/HBN/code_hbn_alcf/job/log.cmd2.t${threads}.${s}
rm -rf $LOG

CMD_sub=/lus/theta-fs0/projects/AD_Brain_Imaging/anal/HBN/code_hbn_alcf/job/cmd2_sub.trac.${s}
rm -rf $CMD_sub


SUBJECT=${s}
#echo ${SUBJECT}

cat<<EOC >$CMD
#!/bin/bash
source ~/.bashrc
workingdir=/lus/theta-fs0/projects/AD_Brain_Imaging/anal/HBN/fs/${s}/dwi_mr
rm -rf \$workingdir
mkdir -p \$workingdir
#cd \$workingdir
mkdir -p /local/scratch/${s}
mkdir -p /local/scratch/${s}/dwi_mr
ssd=/local/scratch/${s}/dwi_mr
cd \$ssd

#####################################################################################################################################
############## COPYING THE INPUT FILES ##############################################################################################
c -fv 5tt_freesurfer_diff_flt_dof6_warped_synant_upsample125.nii.gz \
            WM_FODs_upsample125_norm.mif.gz \
            dtifit_*.nii.gz \
            nodes_*.mif.gz
echo current folder is \`pwd\`
ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=$threads
######################################################################################################################################
######################################################################################################################################
################################### STREAMLINE TRACTOGRAPHY ##############################################################
###########################################(5 Min for 1M)######################################################################################
######################################################################################################################################


###tckgen and connectome (time to 1M for tckgen = 5.5m (50M ;  time to 1M fot tckgen = 5.5M;
time tckgen WM_FODs_upsample125_norm.mif.gz mr_track_20M.tck -act 5tt_freesurfer_diff_flt_dof6_warped_synant_upsample125.nii.gz \
            -backtrack -crop_at_gmwmi -seed_dynamic WM_FODs_upsample125_norm.mif.gz -angle 22.5 -maxlength 250 -minlength 10 \
            -power 1.0 -select 20M -force -nthreads ${threads} && echo 'tckgen done'**********
time tcksift -act 5tt_freesurfer_diff_flt_dof6_warped_synant_upsample125.nii.gz mr_track_20M.tck WM_FODs_upsample125_norm.mif.gz \
            mr_track_10M_SIFT.tck -term_number 10M -force -nthreads ${threads} && echo 'sift done'*******


######################################################################################################################################
######################################################################################################################################
################################### GLOBAL TRACTOGRAPHY ##############################################################
#######################################(30 Min) ##########################################################################################
######################################################################################################################################

time tckglobal mr_dwi_denoised_gibbs_crop_preproc_biasCorr_upsample125.mif.gz \
	response_wm.txt -riso response_csf.txt -riso response_gm.txt \
	-mask mr_mask_upsample125.mif.gz \
	-niter 1e9 \
	-fod WM_FODs_upsample125_norm_global.mif.gz \
	-fiso fiso.mif.gz \
	mr_track_global_1e9.tck -force
            
            

######################################################################################################################################
######################################################################################################################################
################################### tck2connectome ##############################################################
######################################################################################################################################
######################################################################################################################################
fslmaths dtifit_L2 -add dtifit_L3 -div 2 dtifit_RD
imcp dtifit_L1 dtifit_AD

## FA, MD, MO, AD (L1), RD (L2+L3/2)
for dti in FA MD MO AD RD
do 
tcksample mr_track_10M_SIFT.tck dtifit_\${dti}.nii.gz mr_track_10M_SIFT_mean_\${dti}.csv -stat_tck mean -force -nthreads ${threads}
tcksample mr_track_global_1e9.tck dtifit_\${dti}.nii.gz mr_track_global_1e9_mean_\${dti}.csv -stat_tck mean -force -nthreads ${threads}

done

#tcksample mr_track_10M_SIFT.tck dtifit_FA.nii.gz mr_track_10M_SIFT_mean_FA.csv -stat_tck mean -force -nthreads ${threads}
#tcksample mr_track_10M_SIFT.tck dtifit_MD.nii.gz mr_track_10M_SIFT_mean_MD.csv -stat_tck mean -force -nthreads ${threads}
#tcksample mr_track_10M_SIFT.tck dtifit_MO.nii.gz mr_track_10M_SIFT_mean_MO.csv -stat_tck mean -force -nthreads ${threads}
#tcksample mr_track_10M_SIFT.tck dtifit_L1.nii.gz mr_track_10M_SIFT_mean_AD.csv -stat_tck mean -force -nthreads ${threads}
#tcksample mr_track_10M_SIFT.tck dtifit_RD.nii.gz mr_track_10M_SIFT_mean_RD.csv -stat_tck mean -force -nthreads ${threads}


for im in aparc+aseg aparc.a2009s+aseg
do
#1.count
tck2connectome -force -zero_diagonal -nthreads ${threads} \
            mr_track_10M_SIFT.tck nodes_\${im}.mif.gz mr_connectome_sift_10M_\${im}_count.csv
tck2connectome -force -zero_diagonal -nthreads ${threads} \
            mr_track_global_1e9.tck nodes_\${im}.mif.gz mr_connectome_global1e9_\${im}_count.csv
#2.length
tck2connectome -force -zero_diagonal -scale_length -stat_edge mean mr_track_10M_SIFT.tck nodes_\${im}.mif.gz \
            mr_connectome_sift_10M_\${im}_length.csv -nthreads ${threads} 
tck2connectome -force -zero_diagonal -scale_length -stat_edge mean mr_track_global_1e9.tck nodes_\${im}.mif.gz \
            mr_connectome_global1e9_\${im}_length.csv -nthreads ${threads}

#3-7: FA MD M0 AD RD
   for dti in FA MD MO AD RD
   do       

            tck2connectome -force -zero_diagonal -stat_edge mean -scale_file mr_track_10M_SIFT_mean_\${dti}.csv \
                        -nthreads ${threads} mr_track_10M_SIFT.tck nodes_\${im}.mif.gz \
                        mr_connectome_sift_10M_\${im}_\${dti}.csv
            tck2connectome -force -zero_diagonal -stat_edge mean -scale_file mr_track_10M_SIFT_mean_\${dti}.csv \
                        -nthreads ${threads} mr_track_global_1e9.tck nodes_\${im}.mif.gz \
                        mr_connectome_global1e9_\${im}_\${dti}.csv            
   done
done
   
   
#tck2connectome -force -zero_diagonal -stat_edge mean -scale_file mr_track_10M_SIFT_mean_MD.csv -nthreads ${threads} \
#            mr_track_10M_SIFT.tck nodes_\${im}.mif.gz mr_sift_10M_connectome_\${im}_MD.csv
#tck2connectome -force -zero_diagonal -stat_edge mean -scale_file mr_track_10M_SIFT_mean_MO.csv -nthreads ${threads} \
#            mr_track_10M_SIFT.tck nodes_\${im}.mif.gz mr_sift_10M_connectome_\${im}_MO.csv
#tck2connectome -force -zero_diagonal -stat_edge mean -scale_file mr_track_10M_SIFT_mean_AD.csv -nthreads ${threads} \
#            mr_track_10M_SIFT.tck nodes_\${im}.mif.gz mr_sift_10M_connectome_\${im}_AD.csv   
#tck2connectome -force -zero_diagonal -stat_edge mean -scale_file mr_track_10M_SIFT_mean_RD.csv -nthreads ${threads} \
#            mr_track_10M_SIFT.tck nodes_\${im}.mif.gz mr_sift_10M_connectome_\${im}_RD.csv
            
            
######################################################################################################################################
######################################################################################################################################
######################################################################################################################################
######################################################################################################################################
######################################################################################################################################
######################################################################################################################################
     
            
#### COPY ALL THE FILES TO SCRATCH ####
#cp -rfv ../dwi /lus/theta-fs0/projects/AD_Brain_Imaging/anal/HBN/fs/${s}/
#######################################################################
# pigz#
pigz --best -b 1280 -f -T -p ${threads} *mif
pigz --best -b 1280 -f -T -p ${threads} *nii
cp -rfv \$ssd /lus/theta-fs0/projects/AD_Brain_Imaging/anal/HBN/fs/${s}
echo "I THINK EVERYTHING IS DONE BY NOW"
EOC

################################################## END OF CMD##########################################################
chmod +x $CMD


### reference
#echo "aprun -n 1 -N 1 -d 128 -j 2 -cc depth -e OMP_NUM_THREADS=128 $CMD > ./job/log.tckgen.${SUBJECT} 2>&1 &">>$CMD_batch 
echo "aprun -n 1 -N 1 -d ${threads} -j 3 -cc depth -e OMP_NUM_THREADS=${threads} $CMD > $LOG 2>&1 &">>$CMD_batch

echo "sleep 0.2">>$CMD_batch
i=$(($i+1))
echo $i
#echo "execute $CMD_sub"

done

echo "wait" >> $CMD_batch
### batch submission

echo $CMD_batch
chmod +x $CMD_batch
qsub $CMD_batch

#$code/fsl_sub_hpc_2 -s smp,$threads -l /ifs/scratch/pimri/posnerlab/1anal/adni/adni_on_c2b2/job -t $CMD_batch
#$code/fsl_sub_hpc_6 -l /ifs/scratch/pimri/posnerlab/1anal/adni/adni_on_c2b2/job -t $CMD_batch
